
# SERVER
server.port=8081

# DATABASE

# JWT
jwt.secret=${JWT_SECRET}

# Disable Open Session In View
spring.jpa.open-in-view=false

# SWAGGER
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false