
# SERVER
server.port=8081

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/auth-db
spring.datasource.username=root
spring.datasource.password=Skmania@1234

# Show SQL queries in the console
spring.jpa.show-sql=true

# Format SQL output (optional)
spring.jpa.properties.hibernate.format_sql=true

# Automatically update the database schema (use update/create only in dev)
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=ThisIsMySecretKeyForJwtAuthenticationApplication12345678901234567890
jwt.expiration=86400000

# Swagger (keep enabled for development)
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Logging configuration

